version: 2
jobs:
  deploy_mobile:
    working_directory: ~/auxilium
    docker:
      - image: circleci/node:11.8.0
    steps:
      - checkout
      - run:
          name: Install global dependencies
          command: sudo npm i -g yarn@latest && sudo yarn global add expo-cli lerna
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Login to Expo
          command: expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
      - run:
          name: Publish to default channel
          command: yarn workspace @auxilium/app publish:app
      - run:
          name: Publish to Expo Release Channels
          command: |
            if [ "${CIRCLE_BRANCH}" == "staging" ]; then
              yarn workspace @auxilium/app publish:app --release-channel staging
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn workspace @auxilium/app publish:app --release-channel prod
            fi
  build_android:
    working_directory: ~/auxilium
    docker:
      - image: circleci/node:11.8.0
    steps:
      - checkout
      - run:
          name: Install global dependencies
          command: sudo npm i -g yarn@latest && sudo yarn global add expo-cli lerna
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Login to Expo
          command: expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
      - run:
          name: Build Android App
          command: |
            yarn workspace @auxilium/app build:android --release-channel prod
  deploy_backend:
    working_directory: ~/auxilium
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Push backend to Heroku
          command: |
            git subtree push --prefix packages/server https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  deploy:
    jobs:
      - deploy_mobile:
          filters:
            branches:
              only:
                - staging
                - master
      - deploy_backend:
          filters:
            branches:
              only:
                - staging
                - master
      - build_android:
          requires:
            - deploy_mobile
          filters:
            branches:
              only:
                - master
